---
title: "IMML vignette"
author: "Wilhelm Glaas"
date: "`r Sys.Date()`"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(IMLpackage)
options(scipen = 999)

dat <- readRDS("~/Helmholtz/data_IMML/DataPartitioning/dataIDs.rds")
phen <- readRDS("~/Helmholtz/data_IMML/DataPartitioning/mnsi.rds")
```

```{r echo=FALSE}
head(dat)
head(phen)
```

Creating the data partition for the inc3 phenotype

```{r}
part <- DataPartitioning(dataIDs = dat, phenotypeIDs = phen, phenotype = 'inc3')
str(part, list.len = 3)
```

```{r echo=FALSE, out.width='100%', fig.align='center', fig.width=9}

purpose = rep(c('Testing', 'Training'),
                     each = 2)
partition = factor(rep(c(names(part[1]), 'Feature Selection'),
                       times = 2),
                   levels = c(names(part[1]), 'Feature Selection'))
train_amount = c(length(unlist(part$modeltraining$Iteration1$Training)),
                 sum(unlist(lapply(part$trainingFeatureSelection,
                               function(x) length(x[[1]])))))
test_amount = c(length(part$modeltraining$Iteration1$Testing),
                 sum(unlist(lapply(part$testingFeatureSelectionIDs,
                               function(x) length(x[[1]])))))
amount = unlist(c(train_amount, test_amount))
plt_df1 = data.frame(purpose, partition, amount)

purpose = rep(c('Testing', 'Training'),
                     each = length(part$testingFeatureSelectionIDs))
partition = factor(rep(names(part$testingFeatureSelectionIDs), times = 2),
                   levels = c(names(part$testingFeatureSelectionIDs)))
train_amount = unname(lapply(part$trainingFeatureSelection,
                             function(x) length(x[[1]])))
test_amount = unname(lapply(part$testingFeatureSelectionIDs,
                               function(x) length(x[[1]])))
amount = unlist(c(train_amount, test_amount))
plt_df2 = data.frame(purpose, partition, amount)

plt1 = ggplot(plt_df1, aes(x = partition, y = amount,
                   group = purpose, color = purpose, fill = purpose)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75)

plt2 = ggplot(plt_df2, aes(x = partition, y = amount,
                   group = purpose, color = purpose, fill = purpose)) +
  geom_bar(stat = "identity", position = position_dodge(), alpha = 0.75) +
  ggtitle('Feature Selection Modalities')

plt1
plt2
```

```{r inlcude = FALSE, echo=FALSE}
source("~/Helmholtz/IML/R/LogLoss.R")
source("~/Helmholtz/IML/R/caretLogLoss.R")

FsClinical <-
  function(trainIDs,
           testIDs,
           dataIDs,
           phenotypeIDs,
           phenotype,
           clinicalData,
           seed = 123) {

    # Save row names as a column
    dataIDs <- dataIDs %>%
      tibble::rownames_to_column(var = "sampleIDs")
    phenotypeIDs <- phenotypeIDs %>%
      tibble::rownames_to_column(var = "sampleIDs")

    merged <- merge(dataIDs, phenotypeIDs, by = "sampleIDs") %>%
      select(Clinical, any_of(phenotype)) %>% drop_na()

    indicator <- as.vector(merged)[[2]]
    names(indicator) <- as.vector(merged)[[1]]
    indicator <-
      ifelse(indicator == 1, "One", "Zero") %>%
      factor(levels = c("One", "Zero"))

    # Do elastic net
    # Build control
    myControl <- trainControl(
      method = "repeatedcv",
      number = 5,
      repeats = 4,
      savePredictions = "final",
      classProbs = TRUE,
      summaryFunction = CaretLogLoss,
      sampling = NULL,
      allowParallel = TRUE
    )

    # Create variables
    perfList = list()
    var = list()

    # Loop through all partitions
    for (i in 1:length(trainIDs)) {
      cat("Fold", i, "\n")

      # Select the IDs for the partition
      trainID <- unlist(trainIDs[[i]])
      testID <- unlist(testIDs[[i]])

      # Using the rownames of the selected IDs for x also for y
      # NA values are no longer used this way
      xTrain <-
        clinicalData[as.character(trainID),] %>% drop_na()

      yTrain <- indicator[as.character(rownames(xTrain))]

      xTest <- clinicalData[as.character(testID),] %>% drop_na()

      yTest <- indicator[rownames(xTest)]

      weights <-
        ifelse(yTrain == "One", table(yTrain)[[2]] / table(yTrain)[[1]], 1)

      # Building the fit
      set.seed(seed)
      fit <- caret::train(
        x = xTrain,
        y = yTrain,
        method = "glmnet",
        metric = "MyLogLoss",
        tuneLength = 20,
        weights = weights,
        maximize = FALSE,
        trControl = myControl,
        importance = TRUE
      )

      # Building the prediction
      pred <-
        predict(fit, xTest, s = "lambda.min", type = "prob")$One

      roc <-
        roc(
          response = yTest,
          predictor = pred,
          levels = c("Zero", "One")
        )
      auc <- auc(roc)
      perfList[[i]] <- as.numeric(auc)
      varImp <- varImp(fit)$importance
      vari <- varImp$Overall
      names(vari) <- rownames(varImp)
      vari <- vari[order(vari, decreasing = T)]

      var[[i]] <- vari
    }


    # Select best features
    varFil <- lapply(var, function(x)
      names(x[x > 0]))
    varRra <- aggregateRanks(varFil)
    varRra$adjP <- varRra$Score * 100
    varRra$adjP <- p.adjust(varRra$adjP, "fdr")
    varSel <- varRra %>% dplyr::filter(adjP < 0.05)
    varSel <- unname(unlist(select(varSel, "Name")))

    # Save the data
    #saveRDS(dplyr::select(clinicalData, all_of(varSel)),
    #        "clinical_selected.rds")

    result <- select(clinicalData, all_of(varSel))

    return(perfList)
  }

```

```{r}
fsTrain <- part$trainingFeatureSelectionIDs
fsTest <- part$testingFeatureSelectionIDs
```

Clinical Feature Selection

```{r message=FALSE, warning=FALSE}
clin = readRDS("~/Helmholtz/data_IMML/FeatureSelection/clinical/clinical_data.rds")

# aucs = FsClinical(trainIDs = fsTrain$Clinical, testIDs = fsTest$Clinical,
#                   dataIDs = dat, phenotypeIDs = phen, clinicalData = clin,
#                   phenotype = 'inc3', seed = 993)
aucs = readRDS("~/Helmholtz/IML/auc.rds")
```

```{r echo=FALSE, out.width='100%', fig.align='center', fig.width=9}
rm(clin)

plt = ggplot(data.frame(val = unlist(aucs)), aes(val)) + geom_histogram(bins = 40) +
  labs(x = 'AUC values')
plt
```
