package_path: /your/path/IMML/
targets: /your/path/targets.rds
target_name: your_name
modals_ids: /your/path/modals_ids.rds
out_dir: /your/path/out/
seed: 993

data_partitioning:
  k: 5
  n_iterations: 10
  percent: 0.8

feature_selection:
  - modality: Clinical
    data: /your/path/clinical_data.rds
    resampling: False
    n_iterations: 100
    train_split: 0.8
  - modality: Genomics
    file_prefix: /your/path/genomics_processed
    geneloc_file: /your/path/example.gene.loc
    geneset_file: /your/path/geneset.txt
    n_iterations: 100
    train_split: 0.8
  - modality: Methylomics
    data: /your/path/methylomics_data.rds
    pathways: /your/path/pathways_methyl.rds
    dualmap_file: /your/path/dualmap450kEID.rda
    DM_threshold: 2.4e-07
    n_iterations: 100
    train_split: 0.8
  - modality: targeted
    name: Metabolomics
    data: /your/path/metabolomics_data.rds
    pathways: /your/path/metab_pathways.rds
    msea_fdr: 0.2
    resampling: True
    n_iterations: 100
    train_split: 0.8
  - modality: untargeted
    name: Proteomics
    data: /your/path/proteomics_data.rds
    pathways: /your/path/prot_pathways.rds
    resampling: True
    n_iterations: 100
    train_split: 0.8
  - modality: untargeted
    name: Transcriptomics
    data: /your/path/transcriptomics_data.rds
    pathways: /your/path/transc_pathways.rds
    gsea_fdr: 0.2
    resampling: True
    n_iterations: 100
    train_split: 0.8
