package_path: /your/path/IMML/
fs_config_file: /your/path/FS_config.yml

n_iterations: 100
integration: FFS
algorithm: glmnet
p_metric: AUPRC
feature: GSEA
from_clinical: True

annotation_dir: /your/path/here/